# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('profile_type', models.CharField(choices=[('personal', 'Personal Identity'), ('business', 'Business Profile')], default='personal', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, help_text='e.g. Founder & Creative Director', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Brief professional bio or business pitch')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('business_description', models.TextField(blank=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='profiles/logos/')),
                ('business_category', models.CharField(blank=True, help_text='e.g. Technology, Real Estate, Fashion', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp phone number with country code', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, help_text='e.g. Lagos, Nigeria', max_length=150)),
                ('address', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('graphite', 'Graphite Luxury (Dark)'), ('light', 'Clean Light'), ('minimal', 'Monochrome Minimal')], default='graphite', max_length=20)),
                ('is_search_indexed', models.BooleanField(default=True, help_text='Allow search engines to index profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=300)),
                ('icon', models.CharField(default='link', help_text='Icon identifier (e.g., link, globe, briefcase, star, download, calendar)', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_links', to='profiles.profile')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x_twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('whatsapp', 'WhatsApp Channel'), ('telegram', 'Telegram'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('other', 'Other')], max_length=30)),
                ('url', models.CharField(max_length=300)),
                ('display_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
