# Generated by Django 5.2.16 on 2026-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_layout',
            field=models.CharField(choices=[('classic', 'Classic'), ('centered', 'Centered'), ('minimal_layout', 'Minimal'), ('social', 'Social'), ('card', 'Card'), ('executive_layout', 'Executive'), ('brand_header', 'Brand Header'), ('business_card', 'Business Card'), ('business_catalog', 'Business Catalog')], default='classic', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('graphite', 'UZYRA Default'), ('midnight', 'Midnight'), ('ocean', 'Ocean'), ('violet', 'Violet'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('arctic', 'Arctic'), ('sand', 'Sand'), ('executive', 'Executive'), ('navy', 'Navy'), ('emerald_business', 'Emerald Business'), ('royal', 'Royal'), ('burgundy', 'Burgundy'), ('luxury', 'Luxury'), ('platinum', 'Platinum')], default='graphite', max_length=25),
        ),
    ]
