# Generated by Django 5.2.16 on 2026-10-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_profile_layout_expand_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Optional note or context from visitor')),
                ('consent_given', models.BooleanField(default=False, help_text='Explicit user consent given')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contacts', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Contact Exchange Lead',
                'verbose_name_plural': 'Contact Exchange Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
