# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('package_type', models.CharField(choices=[('card_only', 'Smart NFC Card'), ('personal_website', 'Personal Identity (Card + Website)'), ('business_website', 'Business Suite (Card + Business Website)'), ('corporate', 'Corporate / Team Fleet')], default='card_only', max_length=30)),
                ('price_ngn', models.PositiveIntegerField(help_text='Price in Nigerian Naira (NGN)')),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Features separated by newlines')),
                ('badge', models.CharField(blank=True, help_text='e.g. Most Popular, Best Value', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'price_ngn'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Final price paid in NGN')),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Confirmed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('order_status', models.CharField(choices=[('received', 'Order Received'), ('payment_confirmed', 'Payment Confirmed'), ('info_required', 'Information Required'), ('info_submitted', 'Information Submitted'), ('designing', 'Designing & Customizing'), ('review', 'Client Review'), ('production', 'Card Production / Encoding'), ('delivery', 'Out for Delivery'), ('completed', 'Completed & Active')], default='received', max_length=30)),
                ('shipping_name', models.CharField(blank=True, max_length=150)),
                ('shipping_phone', models.CharField(blank=True, max_length=50)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('customer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_assignments', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.productpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('business_category', models.CharField(blank=True, max_length=100)),
                ('business_description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('social_instagram', models.CharField(blank=True, max_length=200)),
                ('social_linkedin', models.CharField(blank=True, max_length=200)),
                ('social_x', models.CharField(blank=True, max_length=200)),
                ('social_tiktok', models.CharField(blank=True, max_length=200)),
                ('social_facebook', models.CharField(blank=True, max_length=200)),
                ('website_url', models.CharField(blank=True, max_length=200)),
                ('website_type', models.CharField(default='none', max_length=50)),
                ('pages_needed', models.CharField(blank=True, help_text='Comma separated pages (Home, About, Services, Gallery, Contact, etc.)', max_length=300)),
                ('design_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='orders.order')),
            ],
        ),
    ]
