# Generated by Django 5.2.16 on 2026-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Order Received'), ('payment_confirmed', 'Payment Confirmed'), ('info_required', 'Information Required'), ('info_submitted', 'Information Submitted'), ('designing', 'Designing & Customizing'), ('review', 'Client Review'), ('production', 'Card Production / Encoding'), ('delivery', 'Out for Delivery'), ('completed', 'Completed & Active'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Confirmed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
