# Generated by Django 5.2.16 on 2026-10-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_otpcode'),
        ('orders', '0003_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='referral code'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Email Verified'), ('qualified', 'Qualified Purchase'), ('rewarded', 'Reward Granted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reward_amount_ngn', models.PositiveIntegerField(default=2000, help_text='Configurable reward value in NGN')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('qualifying_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_referrals', to='orders.order')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
