# Generated by Django 6.1.1 on 2026-09-28 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('card_created', 'Card Created'), ('card_bulk_created', 'Cards Bulk Created'), ('card_assigned', 'Card Assigned'), ('card_reassigned', 'Card Reassigned'), ('card_suspended', 'Card Suspended'), ('card_restored', 'Card Restored'), ('card_marked_lost', 'Card Marked Lost'), ('card_replaced', 'Card Replaced'), ('customer_status_changed', 'Customer Status Changed'), ('website_status_changed', 'Website Status Changed'), ('order_status_changed', 'Order Status Changed')], db_index=True, max_length=40)),
                ('target_repr', models.CharField(help_text='e.g. Card UZY-CARD-000001 or Customer john@example.com', max_length=200)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('previous_state', models.CharField(blank=True, max_length=255)),
                ('new_state', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_admina_action_09f2d5_idx'), models.Index(fields=['target_model', 'target_id'], name='core_admina_target__c70c49_idx')],
            },
        ),
    ]
