# Generated by Django 5.2.16 on 2026-09-30 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('service_type', models.CharField(choices=[('company_team', 'Company & Team NFC Cards'), ('event', 'Event NFC Solutions'), ('event_center', 'Event Center Solutions'), ('security', 'Security Personnel Cards'), ('custom_card', 'Custom Branded NFC Cards'), ('card_website', 'NFC Card + Website'), ('other', 'Other Custom Solution')], default='other', max_length=30)),
                ('estimated_card_quantity', models.CharField(blank=True, help_text='e.g. 50, 100–200, 500+', max_length=50)),
                ('needs_website', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('consultation', 'In Consultation'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal staff notes — not visible to customer.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Inquiry',
                'verbose_name_plural': 'Business Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_busine_status_0195ee_idx'), models.Index(fields=['email'], name='core_busine_email_c9d9a4_idx')],
            },
        ),
    ]
