# Generated by Django 5.2.16 on 2026-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinquiry',
            name='business_type',
            field=models.CharField(blank=True, choices=[('corporate', 'Company / Business'), ('event', 'Event / Conference'), ('event_center', 'Event Center / Venue'), ('security', 'Security Firm'), ('organization', 'Organization / NGO'), ('agency', 'Agency / Creative Studio'), ('retail', 'Retail / Hospitality'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
