# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, help_text='Unique internal ID written to NFC, e.g. BR-000001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned (In Stock)'), ('RESERVED', 'Reserved (Ordered)'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOST', 'Reported Lost'), ('REPLACED', 'Replaced')], db_index=True, default='UNASSIGNED', max_length=20)),
                ('material', models.CharField(choices=[('matte_black', 'Matte Graphite Black'), ('metallic_silver', 'Brushed Silver'), ('carbon_dark', 'Carbon Fiber Minimal')], default='matte_black', max_length=30)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='cards/qrcodes/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='profiles.profile')),
                ('replacement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='cards.card')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['card_code'],
            },
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('nfc_tap', 'NFC Physical Tap'), ('qr_scan', 'QR Code Scan'), ('direct_view', 'Direct Web Visit')], default='nfc_tap', max_length=30)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
