# Generated by Django 6.1.1 on 2026-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activation_code_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hashed secret PIN/code printed on physical packaging', max_length=128, null=True),
        ),
    ]
