# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_type', models.CharField(choices=[('personal', 'Personal Brand Website'), ('business', 'Corporate Business Website')], default='business', max_length=30)),
                ('template_choice', models.CharField(choices=[('modern_business', 'Template 01 — Modern Business & Services'), ('luxury_atelier', 'Template 02 — Luxury Brand & Atelier'), ('creator_portfolio', 'Template 03 — Creator & Professional Portfolio'), ('retail_showcase', 'Template 04 — Retail & Product Showcase')], default='modern_business', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('domain', models.CharField(blank=True, help_text='e.g. www.ahmedphones.com or ahmed.ulva.io', max_length=150)),
                ('live_url', models.URLField(blank=True, help_text='Full external live link')),
                ('status', models.CharField(choices=[('provisioning', 'Setting up Environment'), ('designing', 'In Custom Design'), ('review', 'Client Review'), ('live', 'Active & Live'), ('maintenance', 'Maintenance Mode')], default='designing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Describe the exact text, images, or updates you would like made.')),
                ('status', models.CharField(choices=[('submitted', 'Request Submitted'), ('in_review', 'Under Review'), ('in_progress', 'In Progress'), ('completed', 'Changes Applied & Live')], default='submitted', max_length=30)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_change_requests', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
