# Generated by Django 5.2.16 on 2026-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_builder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft / Designing'), ('published', 'Published & Live'), ('unpublished', 'Unpublished'), ('maintenance', 'Maintenance Mode')], db_index=True, default='draft', max_length=30),
        ),
    ]
