# Generated by Django 5.2.16 on 2026-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_alter_website_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='about_heading',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='about_text',
            field=models.TextField(blank=True, default='', help_text='Custom story / description for About section'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_address',
            field=models.TextField(blank=True, default='', help_text='Physical location or business address'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public inquiry email (defaults to profile email if blank)', max_length=254),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Public phone number (defaults to profile phone if blank)', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default='', help_text='WhatsApp orders / chat number with country code', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_button_text',
            field=models.CharField(default='Chat on WhatsApp', help_text='Primary hero button label', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_button_url',
            field=models.CharField(blank=True, default='', help_text='Optional custom URL for primary hero button', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Hero main headline (defaults to business/profile name if blank)', max_length=150),
        ),
        migrations.AddField(
            model_name='website',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='Contact Us', help_text='Secondary hero button label', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='secondary_cta_url',
            field=models.CharField(blank=True, default='', help_text='Optional custom URL for secondary button', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='tagline',
            field=models.TextField(blank=True, default='', help_text='Hero description / subtitle (defaults to bio if blank)'),
        ),
    ]
