# Generated by Django 5.2.16 on 2026-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_website_about_heading_website_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Chat on WhatsApp', help_text='Primary hero button label', max_length=50),
        ),
    ]
