# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_view', 'Profile View'), ('card_tap', 'NFC Card Tap'), ('qr_scan', 'QR Code Scan'), ('whatsapp_click', 'WhatsApp Click'), ('call_click', 'Phone Call Click'), ('email_click', 'Email Click'), ('website_click', 'External Website Click'), ('social_click', 'Social Media Link Click'), ('vcard_download', 'Saved Contact (vCard)')], db_index=True, max_length=30)),
                ('target_label', models.CharField(blank=True, help_text='e.g. Instagram, Portfolio Button, Call Now', max_length=150)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referer', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='cards.card')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='profiles.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
