# Generated by Django 6.1.1 on 2026-09-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('cards', '0002_card_activation_code_hash'),
        ('profiles', '0001_initial'),
        ('websites', '0002_website_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('profile_view', 'Profile View'), ('card_tap', 'NFC Card Tap'), ('qr_scan', 'QR Code Scan'), ('whatsapp_click', 'WhatsApp Click'), ('call_click', 'Phone Call Click'), ('email_click', 'Email Click'), ('website_click', 'External Website Click'), ('social_click', 'Social Media Link Click'), ('vcard_download', 'Saved Contact (vCard)'), ('website_page_view', 'Website View'), ('website_cta_click', 'Website CTA Click')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['profile', 'timestamp'], name='analytics_a_profile_f73a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['website', 'timestamp'], name='analytics_a_website_3dd6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['card', 'timestamp'], name='analytics_a_card_id_aa14c1_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_a_event_t_64745b_idx'),
        ),
    ]
